export const ReadWriteActionTypes = {
  FLUSH_ACTION_BUFFER: 'FLUSH_ACTION_BUFFER',

  CHANGE_ELEMENT_TREE: 'CHANGE_ELEMENT_TREE',

  REGISTER_COMPONENT_HANDLE: 'REGISTER_COMPONENT_HANDLE',
  UNREGISTER_COMPONENT_HANDLE: 'UNREGISTER_COMPONENT_HANDLE',

  REGISTER_PROP_CONTROLLERS: 'REGISTER_PROP_CONTROLLERS',
  UNREGISTER_PROP_CONTROLLERS: 'UNREGISTER_PROP_CONTROLLERS',
  REGISTER_PROP_CONTROLLERS_HANDLE: 'REGISTER_PROP_CONTROLLERS_HANDLE',
  UNREGISTER_PROP_CONTROLLERS_HANDLE: 'UNREGISTER_PROP_CONTROLLERS_HANDLE',

  REGISTER_MEASURABLE: 'REGISTER_MEASURABLE',
  UNREGISTER_MEASURABLE: 'UNREGISTER_MEASURABLE',

  SET_RESOLVED_VALUE_OVERRIDE: 'SET_RESOLVED_VALUE_OVERRIDE',
  CLEAR_RESOLVED_VALUE_OVERRIDE: 'CLEAR_RESOLVED_VALUE_OVERRIDE',

  UPDATE_API_CLIENT_CACHE: 'UPDATE_API_CLIENT_CACHE',
  CLEAR_API_CLIENT_CACHE: 'CLEAR_API_CLIENT_CACHE',

  FLUSH_MOUNT_CHANGE_ACTIONS: 'FLUSH_MOUNT_CHANGE_ACTIONS',
} as const
