export { default, registerComponent } from './Box'
export {
  DEFAULT_BOX_ANIMATE_TYPE,
  DEFAULT_BOX_ANIMATE_DELAY,
  DEFAULT_BOX_ANIMATE_DURATION,
  DEFAULT_ITEM_ANIMATE_TYPE,
  DEFAULT_ITEM_ANIMATE_DELAY,
  DEFAULT_ITEM_ANIMATE_DURATION,
  DEFAULT_ITEM_STAGGER_DURATION,
} from './animations'
