import '@/components/code-demo/code-demo.makeswift'
import '@/components/font-control-demo/font-control-demo.makeswift'
import '@/components/group-demo/group-demo.makeswift'
import '@/components/icon-radio-group-demo/icon-radio-group-demo.makeswift'
import '@/components/product-image-demo/product-image-demo.makeswift'
import '@/components/slider-demo/slider-demo.makeswift'
