export const STATE_CITIES = {
  Alabama: ['Huntsville', 'Birmingham', 'Montgomery'],
  Alaska: ['Anchorage', 'Fairbanks', 'Juneau'],
  Arizona: ['Phoenix', 'Tucson', 'Mesa'],
  Arkansas: ['Little Rock', 'Fayetteville', 'Fort Smith'],
  California: ['Los Angeles', 'San Diego', 'San Jose'],
  Colorado: ['Denver', 'Colorado Springs', 'Aurora'],
  Connecticut: ['Bridgeport', 'Stamford', 'New Haven'],
  Delaware: ['Wilmington', 'Dover', 'Newark'],
  Florida: ['Jacksonville', 'Miami', 'Tampa'],
  Georgia: ['Atlanta', 'Augusta', 'Columbus'],
  Hawaii: ['Honolulu', 'East Honolulu', 'Pearl City'],
  Idaho: ['Boise', 'Meridian', 'Nampa'],
  Illinois: ['Chicago', 'Aurora', 'Naperville'],
  Indiana: ['Indianapolis', 'Fort Wayne', 'Evansville'],
  Iowa: ['Des Moines', 'Cedar Rapids', 'Davenport'],
  Kansas: ['Wichita', 'Overland Park', 'Kansas City'],
  Kentucky: ['Louisville', 'Lexington', 'Bowling Green'],
  Louisiana: ['New Orleans', 'Baton Rouge', 'Shreveport'],
  Maine: ['Portland', 'Lewiston', 'Bangor'],
  Maryland: ['Baltimore', 'Columbia', 'Germantown'],
  Massachusetts: ['Boston', 'Worcester', 'Springfield'],
  Michigan: ['Detroit', 'Grand Rapids', 'Warren'],
  Minnesota: ['Minneapolis', 'Saint Paul', 'Rochester'],
  Mississippi: ['Jackson', 'Gulfport', 'Southaven'],
  Missouri: ['Kansas City', 'Saint Louis', 'Springfield'],
  Montana: ['Billings', 'Missoula', 'Great Falls'],
  Nebraska: ['Omaha', 'Lincoln', 'Bellevue'],
  Nevada: ['Las Vegas', 'Henderson', 'Reno'],
  'New Hampshire': ['Manchester', 'Nashua', 'Concord'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson'],
  'New Mexico': ['Albuquerque', 'Las Cruces', 'Rio Rancho'],
  'New York': ['New York City', 'Buffalo', 'Rochester'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro'],
  'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks'],
  Ohio: ['Columbus', 'Cleveland', 'Cincinnati'],
  Oklahoma: ['Oklahoma City', 'Tulsa', 'Norman'],
  Oregon: ['Portland', 'Salem', 'Eugene'],
  Pennsylvania: ['Philadelphia', 'Pittsburgh', 'Allentown'],
  'Rhode Island': ['Providence', 'Cranston', 'Warwick'],
  'South Carolina': ['Charleston', 'Columbia', 'North Charleston'],
  'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen'],
  Tennessee: ['Nashville', 'Memphis', 'Knoxville'],
  Texas: ['Houston', 'San Antonio', 'Dallas'],
  Utah: ['Salt Lake City', 'West Valley City', 'West Jordan'],
  Vermont: ['Burlington', 'South Burlington', 'Rutland'],
  Virginia: ['Virginia Beach', 'Chesapeake', 'Norfolk'],
  Washington: ['Seattle', 'Spokane', 'Tacoma'],
  'West Virginia': ['Charleston', 'Huntington', 'Morgantown'],
  Wisconsin: ['Milwaukee', 'Madison', 'Green Bay'],
  Wyoming: ['Cheyenne', 'Casper', 'Laramie'],
} as const satisfies Record<string, string[]>

export type State = keyof typeof STATE_CITIES
