import '@/makeswift/components/clock/clock.makeswift'
import '@/makeswift/components/client-nested-style-test/client-nested-style-test.makeswift'
import '@/makeswift/components/client-group-nested-style-test/client-group-nested-style-test.makeswift'
import '@/makeswift/components/client-styled-render-counter/client-styled-render-counter.makeswift'
import '@/makeswift/components/client-style-v2-test/client-style-v2-test.makeswift'